### ISSUE TITLE
Token seem to be refreshed too often

### ISSUE THREAD

**Issue by fdaveine** [exotic-matter-sas/paper-matter-import-export#12]
See whats wrong is refresh logic or with api response

**Comment by fdaveine** [comment]
> Note: You are 1 hour ahead of server time
In local, Django admin display this warning next to time input, so server might set to a wrong timezone...

**Comment by antoinelibert** [comment]
Server is set to UTC. It's simpler for ops and dev.

**Comment by fdaveine** [comment]
In fact, error only occurred with request launched by `FTLTreeItem.vue`, that was due to a regression introduced by ece4f9565ab3bc8645d83182b8d5cbbcc8f05b1d
